module Config
  UNAME = ENV['GMAIL_UNAME']
  PWORD = ENV['GMAIL_PWORD']
  APPLICATION_NAME = 'Event Creator'
  CLIENT_SECRETS_PATH = ENV['CLIENT_SECRETS_PATH']
  CREDENTIALS_PATH = ENV['CREDENTIALS_PATH']
  CALENDAR_ID = ENV['CALENDAR_ID']
end
